
#include <iostream>

#include "GetWeather.h"

int main(int argc, char *argv[])
{
// Say hello to the world!
    std::cout << "Hello world, a skeleton app generated by appbuild.\n";

// Display the constants defined by app build. \n";
    std::cout << "Application Version " << APP_VERSION << '\n';
    std::cout << "Build date and time " << APP_BUILD_DATE_TIME << '\n';
    std::cout << "Build date " << APP_BUILD_DATE << '\n';
    std::cout << "Build time " << APP_BUILD_TIME << '\n';

//    GetWeather myWeather("__PUT_YOUR_APP_ID_HERE__");
    GetWeather myWeather("47af63a2c9fddca564b02d6ecf080e9d");

    myWeather.Get(50.72824,-1.15244,[](const TheWeather &pTheWeather)
    {

    });

// And quit;
    return EXIT_SUCCESS;
}
